### PR TITLE
update openpyxl to 2.6.4

### PR DESCRIPTION
**Pull request by charity-kwha**
Update `openpyxl` to 2.6.4
[How to update Docker](https://kwhanalytics.atlassian.net/wiki/spaces/KTD/pages/908394665/Updating+the+Insurance+Docker+Image+in-progress)

### CODE REVIEW

**Comment by shutton-kwh** [comment]
Nice, I can see the build in progress on docker hub: https://hub.docker.com/repository/registry-1.docker.io/kwhadocker/insurance-requirements/builds/26f5b2bf-9a80-4dd2-9fa1-d7be8bc59565

**Comment by abshinn** [comment]
@jdunnkwha @shutton-kwh Are any other checks or changes needed before this is merged?

**Comment by jdunnkwha** [comment]
If the Concourse tests pass then we're good to go, this can be merged!

**Comment by abshinn** [comment]
By concourse tests you mean insurance PR concourse tests as well as marvin unit tests, right?
We're good on insurance PR unit tests.
Have marvin unit tests been run?

**Comment by shutton-kwh** [comment]
It looks like we can approve GitHub PRs by clicking the green "Add your Review" button in the upper right.

**Comment by jdunnkwha** [comment]
@abshinn As far as I know, this only needs to pass the insurance unit tests on Concourse that are run when we open a PR. I'm not sure of a way to test this on the marvin unit tests, other than how I tested the original container locally.

**Comment by abshinn** [comment]
I'm not sure either.

@shutton-kwh If we're moving towards a shared image between DE and DS, what is the best way to test if a new requirement works for marvin?

**Comment by shutton-kwh** [comment]
> I'm not sure either.
> 
> @shutton-kwh If we're moving towards a shared image between DE and DS, what is the best way to test if a new requirement works for marvin?

Good point. The testing process for a new marvin docker image will be very similar to the one for a new insurance docker image: we open a marvin PR that updates the "source" line in concourse/test-pipelines/app/app_tests.yaml to point to the new image and then check to see if app tests pass.

**Comment by abshinn** [comment]
@charity-kwha Can you run this one last check in marvin, described by @shutton-kwh?

I imagine it should pass, so hopefully it'll be a quick check.

**Comment by charity-kwha** [comment]
@abshinn running now! [PR#3615](https://bitbucket.org/kwh/marvin/pull-requests/3615/update-docker-tag-point-to-v1-instead-of/diff)

**Comment by abshinn** [comment]
Note: we'll wait until insurance is on Python 3 before upgrading marvin to the latest openpyxl.

**Pull request merged**
